name: SSH Connect_OSTAD

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Connect via SSH (Password)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo "✅ Connected via password!"
            ip addr
            ls
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S apt-get install htop
           
        
          

  

      
