name: SSH Connect_OSTAD

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: self-hosted

    steps:
      
      - name: Beforessh
        run: |
          ip addr
          node -v
          pwd

      - name: Checkout repository_by_masudur
        uses: actions/checkout@v3
  

      
